version: '3'

services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama_container
    ports:
      - "11435:11434"

  spring-ai:
    build: .
    container_name: spring-ai_container
    ports:
      - "8080:8080"
    depends_on:
      - ollama
    environment:
      # Point Spring to Ollama service name
      OLLAMA_BASE_URL: http://ollama:11434        


# springai_default → this is the Docker Compose network created for your SpringAI project.
# Both your spring-ai_container and ollama_container are automatically attached to this network when you run docker compose up. 
# That’s why they can talk to each other using service names.